### ISSUE TITLE
Service keys drop keys with lists

### ISSUE THREAD

**Issue by chrismathias** [mevansam/terraform-provider-cf#11]
Given the following service key of resource cf_service_key.example:
```
{
"client_id": "abc",
"client_secret": "fgj",
"plans": [ "someId"],
"resource_id": "someresource"
}
```
An output statement like
```
output "cf_service_key_example" {
  value = "${cf_service_key.credentials}"
}
```
Will result in the following output: 
```
cf_service_key_example = {
 client_id = abc
 client_secret = fgj
 resource_id = someresource
}
```
The key "plans" is missing. The problem persists when the function "keys" or "jsonencode" is used, the key seems to be dropped when reading the resource.

Extract from the relevant part of the terraform.tfstate file, the "plans" key is missing: 

```
 "cf_service_key.example": {
                    "type": "cf_service_key",
                    "depends_on": [
                        "cf_service_instance.example"
                    ],
                    "primary": {
                        "id": "xyz",
                        "attributes": {
                            "credentials.%": "3",
                            "credentials.client_id": "abc",,
                            "credentials.client_secret": "fqj",
                            "credentials.resource_id": "someresource"
   }
```
Using terraform 0.11.0 and version 0.9.5 of the terraform provider.

**Comment by mevansam** [comment]
@chrismathias It seems like Terraform attribute TypeMap only supports string values and does not support nesting. Would normalizing nested elements into a JSON string work?

**Comment by chrismathias** [comment]
Ideally we would like to be able to directly access the content keys; I don't expect deeper nesting. Would it be possible to use an address pattern like 
plans.0 for the first element of the array, plans.1 etc?

**Comment by mevansam** [comment]
@chrismathias the #cf_service_key# will normalize the credential map by flattening using "_" as the delimiter. It should handle arrays as you requested and should support nesting to any depth.

**Comment by chrismathias** [comment]
That would be great.

**Comment by chrismathias** [comment]
I have tested this, works really nicely. Thanks a lot!
