### ISSUE TITLE
Modify build scripts to allow execution acceptance tests on dev or master branch & clean up systematically

### ISSUE THREAD

**Issue by gberche-orange** [mevansam/terraform-provider-cf#114]
In order to be able to distinguish regressions from instable acceptance environment on failed PR builds.

See https://github.com/mevansam/terraform-provider-cf/blob/2792093b3752b617a5fd31729fa22e9566b6af3b/scripts/build.sh#L5

* [x] concurrency was reduced to 1 in travis: See related exchange https://cloudfoundry.slack.com/archives/C7JRBR8CV/p1529650638000204
* [x] modify build step to systematically run the [clean.sh](https://github.com/mevansam/terraform-provider-cf/blob/dev/tests/clean.sh) script and have it return a zero status to not fail travis
* [x] run the acceptance on every commit on the `dev` and on the `master` branch.

**Comment by janosbinder** [comment]
Adding https://github.com/mevansam/terraform-provider-cf/issues/116 to track failing _github_release_ tests.

**Comment by janosbinder** [comment]
Cleanup is implemented in #122

**Comment by janosbinder** [comment]
Closing the issue as all points have been implemented (#116, #122, #124)
