### ISSUE TITLE
Tests fail using github_release on travis CI due to github api rate limit

### ISSUE THREAD

**Issue by janosbinder** [mevansam/terraform-provider-cf#116]
We have two tests, which fail on the travis CI server, with the following message:
```
...
=== RUN   TestAccBuildpack_normal
--- FAIL: TestAccBuildpack_normal (2.95s)
	testing.go:513: Step 0 error: Error applying: 1 error(s) occurred:
		
		* cloudfoundry_buildpack.tomee: 1 error(s) occurred:
		
		* cloudfoundry_buildpack.tomee: GET https://api.github.com/repos/cloudfoundry-community/tomee-buildpack: 403 API rate limit exceeded for 35.193.203.142. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 17m32.783972333s
...
=== RUN   TestGithubReleaseRepo
Test: release file download
--- FAIL: TestGithubReleaseRepo (0.14s)
	repo_manager_test.go:8: test failed with error: GET https://api.github.com/repos/mevansam/test-app: 403 API rate limit exceeded for 35.193.211.2. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 13m30.209166757s
FAIL
FAIL	github.com/terraform-providers/terraform-provider-cf/cloudfoundry/repo	1.111s
```

Travis CI servers are located in a cloud, where multiple build processes share the same server, thus the same IP. Since github receives anonymous REST calls from other projects, it starts to limit the calls after a while.

I have tried to fix the test, by generating a token in _Settings->Developer Settings->Personal access tokens_, but the rest calls also need the **user name**, which seems not to be implemented in _github_release_, namely in

 https://github.com/mevansam/terraform-provider-cf/blob/432da049e55aa9e29dd8bcef12e7b07dcad60309/cloudfoundry/utils_repo.go#L101

We may need to address this issue, if these failing tests pop up too often in Travis CI.

**Comment by gberche-orange** [comment]
@janosbinder assigning to later milestone for now, lets review this if travis tests fail too often

**Comment by janosbinder** [comment]
Fixed by https://github.com/mevansam/terraform-provider-cf/pull/122
