### ISSUE TITLE
cf_app.github_release + cf_buildpack.github_release should accept username+passwords instead of Oauth access tokens

### ISSUE THREAD

**Issue by gberche-orange** [mevansam/terraform-provider-cf#119]
As mentionned into #116, the cf_app.github_release and cf_buildpack.github_release currently expects an OAuth access token (which includes user identity and permissions as scopes)

https://github.com/mevansam/terraform-provider-cf/blob/dev/website/docs/r/app.html.markdown

> github_release - (Optional, String) The github release where to download the application archive from.
>    owner - (Required, String) The github owner or organization name
>    repo - (Required, String) The repository containing the release
>    token - (Optional, String) Github API token to use to access Github
>    version - (Optional, String) The version or tag of the release.
>    filename - (Required, String) The name of the published file. The values zipball or tarball will download the published

However, this is hard to use for users because:
* OAuth access tokens have an expiration date (usually in days) making them unsuitable for use by CI/CD systems that would invoke TF providers
* OAuth access tokens are best suited for web apps, and thus github does not seem to provide UIs for obtainaing those.

See more background about OAuth token support in github in https://developer.github.com/apps/differences-between-apps/#token-based-identification

Suggested fixes:
* [x] replace the `token` atribute with user name and user password. This provides ability for users to specify a [personal access token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) in place of their main password
* [x] add acceptance test for this case

**Comment by janosbinder** [comment]
Implemented by https://github.com/mevansam/terraform-provider-cf/pull/122
