### ISSUE TITLE
cf_org documentation mentions cf_user_org_role resource but that doesn't seem to exist

### ISSUE THREAD

**Issue by diogomatsubara** [mevansam/terraform-provider-cf#140]
I'm trying to create a new Org in a CF cluster using the terraform cf provider and the documentation mentions that to be able to add OrgManagers, one needs to use the cf_user_org_role resource, but that resource doesn't seem to exist. What would be the proper way of adding a new user as a Org/Space Manager?

**Comment by janosbinder** [comment]
Thanks for pointing out, it has been removed in the development version (see https://github.com/mevansam/terraform-provider-cf/blob/dev/website/docs/r/org.html.markdown ). See some examples in the header of this test: https://github.com/mevansam/terraform-provider-cf/blob/dev/cloudfoundry/resource_cf_user_test.go

If the space/org manager belongs to an UAA group then you can do as it provided in the header of test.

**Comment by diogomatsubara** [comment]
@janosbinder thanks for the pointers!
