### ISSUE TITLE
Invalid wiki links for cloudfoundry_quota pages

### ISSUE THREAD

**Issue by adamzerella** [mevansam/terraform-provider-cf#152]
The wiki sidebar links to the incorrect filenames for `cloudfoundry_quota` references, resulting in a 404.

https://github.com/mevansam/terraform-provider-cf/blob/master/website/docs/d/quota.html.markdown
https://github.com/mevansam/terraform-provider-cf/blob/master/website/docs/r/quota.html.markdown

**Comment by gberche-orange** [comment]
thanks @adamzerella I'll refine the wiki side bar

**Comment by gberche-orange** [comment]
fixed in https://github.com/mevansam/terraform-provider-cf/wiki/_Sidebar/184b07983b50ff84867632a3accd13fefcb91b45
