### ISSUE TITLE
password argument in cloudfoundry_user is not optional

### ISSUE THREAD

**Issue by rparadise** [mevansam/terraform-provider-cf#178]
According to the documentation: "password - (Optional) The user's password"
Ref: https://github.com/mevansam/terraform-provider-cf/blob/master/website/docs/r/user.html.markdown

Declaring a cloudfoundry_user resource with only the name as argument should be sufficient. However, the terraform plan throws an error.

`data "cloudfoundry_user" "MYUSER" {
  name = "MYUSER"
  
}` 

terraform plan -out=plan.out

`...
cloudfoundry_user.MYUSER: Server error, status code: 400, error code: invalid_password, message: Password must be at least 1 characters in length.
...`

Is the behaviour expected?

Thanks

**Comment by janosbinder** [comment]
Thanks for your note. We assume that the server's policy requires to have a password set for the user. Does this user have a password?

**Comment by rparadise** [comment]
This user does not have a password since it has a UAA origin.

**Comment by gberche-orange** [comment]
@rparadise can you please provide the exact tf configuration you're trying to apply, and the corresponding CF CLI command which you expect to be applied as a result ?

https://docs.cloudfoundry.org/adminguide/cli-user-management.html 

Would you be missing the `origin` flag ?

**Comment by rparadise** [comment]
Thanks @gberche-orange for your input. Actually, I missed providing the correct name of Identity Provider, the value in the PAS tile,the "Provider Name" in the SSO section.

I was confused by the By Default "UAA" value of the origin's argument. 

So this is not an issue. I appreciate your input

regards

Rparadise
