### ISSUE TITLE
wrong directory in installation instructions

### ISSUE THREAD

**Issue by abendt** [mevansam/terraform-provider-cf#191]
I think the installation instructions in the wiki are a bit misleading. I think the location of the terraform plugins directory should be _~/.terraform.d/.._ not _~/terraform.d/.._

I have prepared a patch for the wiki codebase (https://github.com/mevansam/terraform-provider-cf.wiki.git)

[update-installation-doc.txt](https://github.com/mevansam/terraform-provider-cf/files/3124342/update-installation-doc.txt)

**Comment by gberche-orange** [comment]
thanks @abendt fixed in https://github.com/mevansam/terraform-provider-cf/wiki/Home/cc722e138983b1c846f16b06bbb852a7095229de, see https://github.com/mevansam/terraform-provider-cf/wiki/Home/_history
