### ISSUE TITLE
documentation link to resource "route service binding" is missing

### ISSUE THREAD

**Issue by abendt** [mevansam/terraform-provider-cf#192]
It seems that the documentation link to https://github.com/mevansam/terraform-provider-cf/blob/master/website/docs/r/route_service_binding.html.markdown is missing in the sidebar: https://github.com/mevansam/terraform-provider-cf/wiki

I've prepared a patch that adds the link:

[add-missing-link.txt](https://github.com/mevansam/terraform-provider-cf/files/3124353/add-missing-link.txt)

**Comment by gberche-orange** [comment]
Thanks @abendt !

Fixed in https://github.com/mevansam/terraform-provider-cf/wiki/_Sidebar/f3761d2c2b6cb34c6601c4ff7b29a48dea2795cd see https://github.com/mevansam/terraform-provider-cf/wiki/_Sidebar/_history
