### ISSUE TITLE
0.9.8 release build failing on TestAccSpace_importBasic

### ISSUE THREAD

**Issue by gberche-orange** [mevansam/terraform-provider-cf#28]
See https://travis-ci.org/mevansam/terraform-provider-cf/builds/338978050#L658

@ArthurHlt can you please have a look ?

**Comment by ArthurHlt** [comment]
Fixed by https://github.com/mevansam/terraform-provider-cf/commit/7a997613e5716b1a9efce6bc03caa6bd2d98bcda 
this will ignore test for security groups import. I was trying, in the first, to retrieve the default security group made by cloud foundry but it seems that name is changing.
