### ISSUE TITLE
unable to get org id

### ISSUE THREAD

**Issue by lakamsani** [mevansam/terraform-provider-cf#29]
Using code like this: 
```bash
data "cf_org" "myorg" {
  name = "${var.org_name}"
}

output "org_id" {
  value = "${cf_org.myorg.id}"
}
```

`terraform plan` triggers an error on the `cf_org.myorg.id` line:

```bash
Error: output 'org_id': unknown resource 'cf_org.myorg' referenced in variable cf_org.myorg.id
```
What can be fixed to make this work? 

A second question is related to `vars` that collect passwords like:

```bash
variable "password" {
  description = "IBM Cloud Password"
  type = "string"
}
```
When `terraform plan` is run, and user is typing the password it shows it in clear text. Is there a `type` setting that can be used to mask the password with say `*****`?

**Comment by psycofdj** [comment]
Try the following:

´´´ 
data "cf_org" "myorg" {
  name = "${var.org_name}"
}

output "org_id" {
  value = "${data.cf_org.myorg.id}"
}
´´´ 

For password input, you can use [variable files](https://www.terraform.io/intro/getting-started/variables.html)

**Comment by lakamsani** [comment]
That works. Thanks.
