### ISSUE TITLE
Application Binding to Service Instances fail

### ISSUE THREAD

**Issue by samedguener** [mevansam/terraform-provider-cf#40]
Dear contributors,

Binding an application to a service instance fails, when the service instance takes a long time to start.
Our service instances (such as postgresql) on our production environment takes approx. 5-7 mins to start. While the service instance is still starting, Terraform tries to bind the application to the service instance and it fails with following output.

``` Error: Error applying plan:

2 error(s) occurred:

* module.ca-components.cf_app.a: 1 error(s) occurred:

* cf_app.a: Server error, status code: 409, error code: 60016, message: An operation for service instance db is in progress.
* module.ca-components.cf_app.b: 1 error(s) occurred:

* cf_app.b: Server error, status code: 409, error code: 60016, message: An operation for service instance db is in progress.
```
When a service instance is created, Terraform assumes that the service instance has been started, while this is not the case as shown previously.

I proposed a solution for this in [#41](https://github.com/mevansam/terraform-provider-cf/pull/41). In this solution we request the CF API for the status of the created service instance. We wait until the service instance is started.

If there are any open questions, please free to ask.

Best,
Samed

**Comment by gberche-orange** [comment]
addressed by #111
