### ISSUE TITLE
Missing error checks

### ISSUE THREAD

**Issue by gberche-orange** [mevansam/terraform-provider-cf#49]
This is a split of #38 

> Missing error checks (found with `errcheck`), if these are meant to be explicit use `_` and possibly comment as to why the error is discarded, and you should definitely log the error so it can be found in trace if desired

**Comment by ArthurHlt** [comment]
`errcheck` give a lot of non-check function but some of them should not be considere as not checked like:
- `github.com/hashicorp/terraform/helper/schema.ResourceData.Set()` as every provider doesn't check this error (we may found [this](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_ami.go#L265) as an example)
- `defer` keyword which act like `finally` in java, error give by defer should not be check (it's the function associate to defer which provide one normally)

**Comment by ArthurHlt** [comment]
I'm providing an `errcheck_excludes.txt` file as `ignore` in [errcheck is deprecated](https://github.com/kisielk/errcheck#the-deprecated-method) but i will create this file in the same way as hashicorp do, see: https://github.com/terraform-providers/terraform-provider-aws/blob/master/scripts/errcheck.sh#L11-L15

**Comment by ArthurHlt** [comment]
I've updated `scripts/errcheck.sh` with additional false positive on defer:

```
-ignore 'archive/zip:Close|Write' \
-ignore 'os:Close|Write|Remove|RemoveAll' \
-ignore 'compress/gzip:Close|Write' \
```

**Comment by ArthurHlt** [comment]
Fixed bunch of missing errors:

```
cloudfoundry/cfapi/service_manager.go:784:37:	sm.ccGateway.ListPaginatedResources(sm.apiEndpoint, path, CCServiceInstanceRouteResource{}, func(route interface{}) bool {
cloudfoundry/resource_cf_app.go:417:16:	am.DeleteApp(app.ID, true)
cloudfoundry/resource_cf_app.go:706:14:	am.DeleteApp(d.Id(), false)
cloudfoundry/resource_cf_route.go:139:18:	rm.DeleteRoute(route.ID)
cloudfoundry/resource_cf_user.go:200:11:	um.Delete(id)
``` 

**Note**: `sm.ccGateway.ListPaginatedResources` has been checked with fix for naked return.

See commit: https://github.com/mevansam/terraform-provider-cf/commit/7ee9770ac9bf269e1d96851961a38ae78654edc8
