### ISSUE TITLE
Add support for shared private domains in cf_domain resource

### ISSUE THREAD

**Issue by gberche-orange** [mevansam/terraform-provider-cf#5]
Currently, the [cf_domain](https://github.com/mevansam/terraform-provider-cf/blob/master/website/docs/r/domain.html.markdown) accepts a single org guid:

> org - (Optional, String) The GUID of the Org that owns this domain. If provided then this will be a private domain.

We need to share private domains across multiple orgs in the similar to the ``cf share-private-domain test-org private-domain.example.com`` CLI commands support, see http://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#private-domains and related [PUT /v2/organizations/:guid/private_domains/:private_domain_guid](http://apidocs.cloudfoundry.org/280/organizations/associate_private_domain_with_the_organization.html) CC API call

Adding a new `shared_with_orgs` parameter with the following semantic could be a way to address this use-case

> shared_with_orgs - (Optional, Array of String) The GUID of the Orgs that are shared the private domain owned by the org specified in the `org` argument. Errors if the `org` argument is undefined (i.e. if the domain is a public shared domain).

**Comment by psycofdj** [comment]
:+1: We indeed need to implement the sharing of private domains among multiple organizations.

However, I see some a problems with your proposal. 

The ```shared_with_orgs``` attributes suggests that all authorized organizations must be listed in this single ```cf_domain``` resource. This would prevent users to separate the configuration of the domain and its access (ie: in multiple `.tf` files or in multiple states)

What about an approach similar to the `cf_service_access` ? We could add a resource that represent additional sharing of a domain to an organization ```cf_domain_access``` or ```cf_domain_share```

**Proposal**

```
data "cf_org" "org1" {
  name = "org1"
}

data "cf_org" "org2" {
  name = "org2"
}

data "cf_org" "org3" {
  name = "org3"
}

resource "cf_domain" "my-shared-domain" {
  name = "pcfdev-org.io"
  # org declared in cf_domain is the owning org of the private domain
  org = "${data.org1.id}" 
}

resource "cf_domain_access" "shared-to-org2" {
  domain = "${cf_domain.my-shared-domain.id}"
  org = "${data.org2.id}"
}

resource "cf_domain_access" "shared-to-org3" {
  domain = "${cf_domain.my-shared-domain.id}"
  org = "${data.org3.id}"
}
```

This would allow to create multiple "cf_domain_access" in multiple `.tf` files.

In the previous example, `org1` owns the private domain, `org2` and `org3` only have a shared access to the domain.

Remark: In CF, there is a notion of `owning` organization regarding to a domain. 


### Implementation

From the CF API's point of view, access to private domains is an association between existing organizations and existing domains. In other words, there is no object in CF with its own `guid` that represent this access.

Giving an org access to a private domain translates in the following API command :
```
# Request:
PUT /v2/organizations/<ord-guid>/private_domains/<domain-guid>

# Response
{ org-data }
```

Not having an `id` representing this access is a problem for the ```cf_domain_access``` resource. 

A solution could be to use a concatenation of ```<org-guid>/<domain-guid>``` as resource identifier to store into the state and also as import parameter.
```

**Comment by gberche-orange** [comment]
Thanks @psycofdj for this great suggestion. I support the idea of a distinct `cf_domain_access` resource. 

I'd suggest to make it explicit this resource relates to *private* domain sharing, either by:
1 - naming the resource `cf_private_domain_access`
2- naming the `cf_domain_access.domain` attribute `private_domain`

resource "cf_domain_access" "shared-to-org3" {
  domain = "${cf_domain.my-shared-domain.id}"
  org = "${data.org3.id}"
}

I have a preference of 1)
