### ISSUE TITLE
Rework cf_app local download to use ioutil.Temp & clean up temp files

### ISSUE THREAD

**Issue by gberche-orange** [mevansam/terraform-provider-cf#57]
This is a split of #38 

> It seems like the repo package is pulling a release locally, modifying it, and then it will be pushed up to Cloud Foundry as part of the resource_cf_app, is that understanding correct? You should switch to using the ioutil.Temp* methods instead of having the case where it uses the home directory. Also, please make sure to clean up any temp files or directories the provider creates during its execution.

**Comment by ArthurHlt** [comment]
Close in favor of PR https://github.com/mevansam/terraform-provider-cf/pull/70
