### ISSUE TITLE
check which optional attributes should have a default

### ISSUE THREAD

**Issue by gberche-orange** [mevansam/terraform-provider-cf#59]
This is a follow up of #38 

> For resource schema, if you have an optional attribute, typically (but not always) you would include a default.

**Comment by gberche-orange** [comment]
Current list of optional attributes without documented default. We should at least document the default behavior when the attribute is omitted


> $ grep -rin optional website/ | grep -vi default 
> website/docs/r/space.html.markdown:45:* `quota` - (Optional) The ID of the Space [quota](/docs/providers/cloudfoundry/r/quota.html) or plan defined for the owning Org.
> website/docs/r/space.html.markdown:46:* `allow_ssh` - (Optional) Allows SSH to application containers via the [CF CLI](https://github.com/cloudfoundry/cli)
> website/docs/r/space.html.markdown:47:* `asgs` - (Optional) List of running [application security groups](/docs/providers/cloudfoundry/r/asg.html) to apply to applications running within this space.
> website/docs/r/space.html.markdown:48:* `staging_asgs` - (Optional) List of staging [application security groups](/docs/providers/cloudfoundry/r/asg.html) to apply to applications being staged for this space.
> website/docs/r/space.html.markdown:49:* `managers` - (Optional) List of users to assign [SpaceManager](https://docs.cloudfoundry.org/concepts/roles.html#roles) role to.
> website/docs/r/space.html.markdown:50:* `developers` - (Optional) List of users to assign [SpaceDeveloper](https://docs.cloudfoundry.org/concepts/roles.html#roles) role to.
> website/docs/r/space.html.markdown:51:* `auditors` - (Optional) List of users to assign [SpaceAuditor](https://docs.cloudfoundry.org/concepts/roles.html#roles) role to.
> website/docs/r/service_broker.html.markdown:32:* `username` - (Optional) The user name to use to authenticate against the service broker API calls
> website/docs/r/service_broker.html.markdown:33:* `password` - (Optional) The password to authenticate with
> website/docs/r/service_broker.html.markdown:34:* `space` - (Optional) The ID of the space to scope this broker to
> website/docs/r/domain.html.markdown:40:* `sub_domain` - (Optional, String) Sub-domain part of full domain name. If specified the `domain` argument needs to be provided and the `name` will be computed.
> website/docs/r/domain.html.markdown:41:* `domain` - (Optional, String) Domain part of full domain name. If specified the `sub_domain` argument needs to be provided and the `name` will be computed.
> website/docs/r/domain.html.markdown:45:* `router_group` - (Optional, String) The router group GUID, which can be retrieved via the [`cf_router_group`](/docs/providers/cf/d/stack.html) data resource. You would need to provide this when creating a shared domain for TCP routes.
> website/docs/r/domain.html.markdown:49:* `org` - (Optional, String) The GUID of the Org that owns this domain. If provided then this will be a private domain.
> website/docs/r/asg.html.markdown:48:  - `type` - (Optional) Allowed ICMP [type](https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml#icmp-parameters-types).
> website/docs/r/asg.html.markdown:49:  - `code` - (Optional) Allowed ICMP [code](https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml#icmp-parameters-codes).
> website/docs/r/asg.html.markdown:50:  - `log` - (Optional) Set to `true` to enable logging. For more information on how to configure system logs to be sent to a syslog drain, review the [ASG logging](http://docs.cloudfoundry.org/concepts/asg.html#logging) documentation.
> website/docs/r/asg.html.markdown:51:  - `description` - (Optional) Description of the rule.
> website/docs/r/user.html.markdown:36:* `password` - (Optional) The user's password
> website/docs/r/user.html.markdown:38:* `given_name` - (Optional) The given name of the user
> website/docs/r/user.html.markdown:39:* `family_name` - (Optional) The family name of the user
> website/docs/r/user.html.markdown:40:* `email` - (Optional) The email address of the user
> website/docs/r/user.html.markdown:41:* `groups` - (Optional) Any UAA `groups` / `roles` to associated the user with
> website/docs/r/route.html.markdown:31:- `hostname` - (Required, Optional) The application's host name. This is required for shared domains.
> website/docs/r/route.html.markdown:35:- `port` - (Optional, Int) The port to associate with the route for a TCP route. 
> website/docs/r/route.html.markdown:36:- `random_port` - (Optional, Bool) Set to 'true' to create a random port.
> website/docs/r/route.html.markdown:40:- `path` - (Optional) A path for a HTTP route.
> website/docs/r/route.html.markdown:44:- `target` - (Optional) A route mapping that will map this route to an application
> website/docs/r/buildpack.html.markdown:31:* `position` - (Optional, Number) Specifies where to place the buildpack in the detection priority list. For more information, see the [Buildpack Detection](https://docs.cloudfoundry.org/buildpacks/detection.html) topic.
> website/docs/r/buildpack.html.markdown:39:* `url` - (Optional, String) Specifies the location of the buildpack to upload from. It can be a URL to a zip file, a github repository or a local directory via "`file://...`".
> website/docs/r/buildpack.html.markdown:41:* `git` - (Optional, String) The git location to pull the builpack source directly from source control.
> website/docs/r/buildpack.html.markdown:44:  - `branch` - (Optional, String) The branch of from which the repository contents should be retrieved.
> website/docs/r/buildpack.html.markdown:45:  - `tag` - (Optional, String) The version tag of the contents to retrieve.
> website/docs/r/buildpack.html.markdown:46:  - `user` - (Optional, String) Git user for accessing a private repo.
> website/docs/r/buildpack.html.markdown:47:  - `password` - (Optional, String) Git password for accessing a private repo.
> website/docs/r/buildpack.html.markdown:48:  - `key` - (Optional, String) The git private key to access a private repo via SSH.
> website/docs/r/buildpack.html.markdown:52:* `github_release` - (Optional, String) The Buildpack archive published as a github release.
> website/docs/r/buildpack.html.markdown:55:  - `token` - (Optional, String) Github API token to use to access Github.
> website/docs/r/buildpack.html.markdown:56:  - `version` - (Optional, String) The version or tag of the release.
> website/docs/r/quota.html.markdown:52:* `instance_memory` - (Optional) Maximum memory per application instance
> website/docs/r/quota.html.markdown:54:* `total_app_instances` - (Optional) Maximum app instances allowed
> website/docs/r/quota.html.markdown:57:* `total_route_ports` - (Optional) Maximum routes with reserved ports
> website/docs/r/quota.html.markdown:58:* `total_private_domains` - (Optional) Maximum number of private domains allowed to be created within the Org
> website/docs/r/quota.html.markdown:59:* `org` - (Optional) The Org within which this quota will be defined so it can be applied to spaces within that Org
> website/docs/r/org.html.markdown:29:* `quota` - (Optional) The quota or plan to be given to this Org
> website/docs/r/org.html.markdown:30:* `managers` - (Optional) List of users to assign [OrgManager](https://docs.cloudfoundry.org/concepts/roles.html#roles) role to
> website/docs/r/org.html.markdown:31:* `billing_managers` - (Optional) List of users to assign [BillingManager](https://docs.cloudfoundry.org/concepts/roles.html#roles) role to
> website/docs/r/org.html.markdown:32:* `auditors` - (Optional) List of users to assign [OrgAuditor](https://docs.cloudfoundry.org/concepts/roles.html#roles) role to
> website/docs/r/app.html.markdown:30:* `ports` - (Optional, Array of Number) A list of ports which the app will listen on.
> website/docs/r/app.html.markdown:31:* `instances` - (Optional, Number) The number of app instances that you want to start.
> website/docs/r/app.html.markdown:32:* `memory` - (Optional, Number) The memory limit for each application instance in megabytes.
> website/docs/r/app.html.markdown:33:* `disk_quota` - (Optional, Number) The disk space to be allocated for each application instance in megabytes.
> website/docs/r/app.html.markdown:35:* `buildpack` - (Optional, String) The custom buildpack to use. This will bypass the buildpack detect phase. There are three options to choose from:
> website/docs/r/app.html.markdown:37:* `command` - (Optional, String) A custom start command for the application. This overrides the start command provided by the buildpack.
> website/docs/r/app.html.markdown:39:* `timeout` - (Optional, Number) Max wait time for app instance startup, in seconds
> website/docs/r/app.html.markdown:46:* `url` - (Optional, String) The URL for the application binary. A local path may be referenced via "`file://...`".
> website/docs/r/app.html.markdown:48:* `git` - (Optional, String) The git location to pull the application source directly from source control.
> website/docs/r/app.html.markdown:51:  - `branch` - (Optional, String) The branch of from which the repository contents should be retrieved.
> website/docs/r/app.html.markdown:52:  - `tag` - (Optional, String) The version tag of the contents to retrieve.
> website/docs/r/app.html.markdown:53:  - `key` - (Optional, String) The git private key to access a private repo via SSH.
> website/docs/r/app.html.markdown:54:  - `user` - (Optional, String) Git user for accessing a private repo.
> website/docs/r/app.html.markdown:55:  - `password` - (Optional, String) Git password for accessing a private repo.
> website/docs/r/app.html.markdown:59:* `github_release` - (Optional, String) The Buildpack archive published as a github release.
> website/docs/r/app.html.markdown:63:  - `token` - (Optional, String) Github API token to use to access Github
> website/docs/r/app.html.markdown:64:  - `version` - (Optional, String) The version or tag of the release.
> website/docs/r/app.html.markdown:67:* `add_content` - (Optional, Array) adds the given content from a local path to the application directory. You can use this attribute to inject files into the pushed application source.
> website/docs/r/app.html.markdown:76:* `service_binding` - (Optional, Array) Service instances to bind to.
> website/docs/r/app.html.markdown:79:  - `params` - (Optional, Map) A list of key/value parameters used by the service broker to create the binding.
> website/docs/r/app.html.markdown:83:* `route` - (Optional) Configures how the application or service will be accessed. This can be also used to define a blue-green app deployment strategy. When doing a blue-green deployment the actual name of the application will be timestamped to differentiate between the current live application and the more recent staged application.
> website/docs/r/app.html.markdown:89:  - `stage_route` - (Optional, String) The GUID of the route where the staged application will be available.
> website/docs/r/app.html.markdown:90:  - `live_route` - (Optional, String) The GUID of the route where the live application will be available.
> website/docs/r/app.html.markdown:91:  - `validation_script` - (Optional, String) The validation script to execute against the stage application before mapping the live route to the staged application.
> website/docs/r/app.html.markdown:97:* `environment` - (Optional, Map) Key/value pairs of all the environment variables to run in your app. Does not include any system or service variables.
> website/docs/r/app.html.markdown:103:* `health_check_timeout` - (Optional, Number) The timeout in seconds for the health check.
> website/docs/r/service_key.html.markdown:40:* `params` - (Optional, Map) A list of key/value parameters used by the service broker to create the binding for the key.
> website/docs/r/service_plan_access.html.markdown:36:* `org` - (Optional) The ID of the Org which should have access to the plan. Conflicts with `public`.
> website/docs/r/service_plan_access.html.markdown:37:* `public` - (Optional) Boolean that controls the public state of the plan. Conflicts with `org`.
> website/docs/r/service_instance.html.markdown:36:* `json_params` - (Optional, String) Json string of arbitrary parameters. Some services support providing additional configuration parameters within the provision request
> website/docs/r/service_instance.html.markdown:37:* `tags` - (Optional, List) List of instance tags. Some services provide a list of tags that Cloud Foundry delivers in [VCAP_SERVICES Env variables](https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#VCAP-SERVICES)
> website/docs/r/user_provided_service.html.markdown:53:* `credentials` - (Optional) Arbitrary credentials in the form of key-value pairs and delivered to applications via [VCAP_SERVICES Env variables](https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#VCAP-SERVICES). Conflicts with `credentials_json`.
> website/docs/r/user_provided_service.html.markdown:54:* `credentials_json` - (Optional) Same as `credentials` but in the form of a stringified JSON object. Conflicts with `credentials`.
> website/docs/r/user_provided_service.html.markdown:55:* `syslog_drain_url` - (Optional) URL to which logs for bound applications will be streamed
> website/docs/r/user_provided_service.html.markdown:56:* `route_service_url` - (Optional) URL to which requests for bound routes will be forwarded. Scheme for this URL must be https
> website/docs/r/config.html.markdown:43:  - `user_org_creation` - (Optional) Any user can create an organization. Minimum CC API version: 2.12.
> website/docs/r/config.html.markdown:44:  - `private_domain_creation` - (Optional) An Org Manager can create private domains for that organization. Minimum CC API version: 2.12.
> website/docs/r/config.html.markdown:45:  - `app_bits_upload` - (Optional) Space Developers can upload app bits. Minimum CC API version: 2.12.
> website/docs/r/config.html.markdown:46:  - `app_scaling` - (Optional) Space Developers can perform scaling operations (i.e. change memory, disk, or instances). Minimum CC API version: 2.12.
> website/docs/r/config.html.markdown:47:  - `route_creation` - (Optional) Space Developers can create routes in a space. Minimum CC API version: 2.12.
> website/docs/r/config.html.markdown:48:  - `service_instance_creation` - (Optional) Space Developers can create service instances in a space. Minimum CC API version: 2.12.
> website/docs/r/config.html.markdown:49:  - `diego_docker` - (Optional) Space Developers can push Docker apps. Minimum CC API version 2.33.
> website/docs/r/config.html.markdown:50:  - `set_roles_by_username` - (Optional) Org Managers and Space Managers can add roles by username. Minimum CC API version: 2.37.
> website/docs/r/config.html.markdown:51:  - `unset_roles_by_username` - (Optional) Org Managers and Space Managers can remove roles by username. Minimum CC API version: 2.37.
> website/docs/r/config.html.markdown:52:  - `task_creation` - (Optional) Space Developers can create tasks on their application. This feature is under development. Minimum CC API version: 2.47.
> website/docs/r/config.html.markdown:53:  - `env_var_visibility` - (Optional) All users can view environment variables. Minimum CC API version: 2.58.
> website/docs/r/config.html.markdown:54:  - `space_scoped_private_broker_creation` - (Optional) Space Developers can create space-scoped private service brokers. Minimum CC API version: 2.58.
> website/docs/r/config.html.markdown:55:  - `space_developer_env_var_visibility` - (Optional) Space Developers can view their v2 environment variables. Org Managers and Space Managers can view their v3 environment variables. Minimum CC API version: 2.58.
> website/docs/r/route_service_binding.html.markdown:30:* `json_params` - (Optional, String) Arbitrary parameters in the form of stringified JSON object to pass to the service bind handler.
> website/docs/d/space.html.markdown:32:* `org` - (Optional) GUID of the organization the space belongs to.
> website/docs/d/space.html.markdown:33:* `org_name` - (Optional) Name of the organization the space belongs to.
> website/docs/d/domain.html.markdown:27:* `name` - (Optional) This value will be computed based on the `sub-domain` or `domain` attributes. If provided then this argument will be used as the full domain name.
> website/docs/d/domain.html.markdown:28:* `sub-domain` - (Optional) The sub-domain of the full domain name
> website/docs/d/domain.html.markdown:29:* `domain` - (Optional) The domain name
> website/docs/d/quota.html.markdown:29:* `org` - (Optional) The organization within which the quota is defined
> website/docs/d/service_key.html.markdown:29:* `space` - (Optional, String) The space where the service key was created.
> website/docs/d/service_instance.html.markdown:29:* `space` - (Optional, String) The space within which the service instance has been created.
> website/docs/d/service.html.markdown:37:* `space` - (Optional) The space within which the service is defined
>

**Comment by gberche-orange** [comment]
fixed by #76

**Comment by gberche-orange** [comment]
waiting until #76 gets merged

**Comment by janosbinder** [comment]
https://github.com/mevansam/terraform-provider-cf/pull/76 is merged - closing the issue.
