### ISSUE TITLE
Split cf_quota resource into cf_org_quota and cf_space_quota

### ISSUE THREAD

**Issue by gberche-orange** [mevansam/terraform-provider-cf#69]
The current [cf_quota](https://github.com/mevansam/terraform-provider-cf/blob/master/website/docs/r/quota.html.markdown) resources tries to provision two distinct underlying CF resource types, and have users select among the two types using the `org` attribute
* [Org quota definition /v2/quota_definitions](http://apidocs.cloudfoundry.org/1.24.0/organization_quota_definitions/creating_a_organization_quota_definition.html)
* [Space Quota Definition /v2/space_quota_definitions](http://apidocs.cloudfoundry.org/1.24.0/space_quota_definitions/creating_a_space_quota_definition.html)

> * `org` - (Optional) The Org within which this quota will be defined so it can be applied to spaces within that Org

The actual value of the org parameter is ignored, only its presence/absence seems used in the code:
https://github.com/mevansam/terraform-provider-cf/blob/0dfaf692eb587f5e94a1b44a129bde8f6bb7da67/cloudfoundry/cfapi/quota_manager..go#L85-L96

Since both the CF CLI and the CF CC API manage distinct objects (that may evolve independently), it would make more sense to expose two distinct CF resources. Also, trying to hide both concepts makes documentation wording complex and error prone.

> $ cf help -a | grep quota
>    quotas                                 List available usage quotas
>    quota                                  Show quota info
>    set-quota                              Assign a quota to an org
>    create-quota                           Define a new resource quota
>    delete-quota                           Delete a quota
>    update-quota                           Update an existing resource quota
>    space-quotas                           List available space resource quotas
>    space-quota                            Show space quota info
>    create-space-quota                     Define a new space resource quota
>    update-space-quota                     Update an existing space quota
>    delete-space-quota                     Delete a space quota definition and unassign the space quota from all spaces
>    set-space-quota                        Assign a space quota definition to a space
>    unset-space-quota                      Unassign a quota from a space
> 

Marking as 1.0 milestone to avoid backward incompatibilities

**Comment by janosbinder** [comment]
This has been also merged and finished @gberche-orange or?

**Comment by gberche-orange** [comment]
yes this was fixed by #77, thanks for the heads up
