### ISSUE TITLE
Service plans are not parsed correctly if the name contains "."

### ISSUE THREAD

**Issue by chrismathias** [mevansam/terraform-provider-cf#7]
Hi,
We have come accross the following problem. In our environment we are using a database service with two service plans: 
"v3.0-dev"
"v3.0-dev-small"

When reading the service plans into terraform via
```
data "cf_service" "sv_database" {
  name = "somedatabase"
}
```
Then I would expect that data.cf_service.sv_database.service_plans looks like this: 
```
{ 
v3.0-dev = "some guid A"
v3.0-dev-small = "some guid B"
}
```

However, what is actually parsed (verifiable with the output command) is this: 

```
{   v3 = {
       0-dev = "some guid A"
       0-dev-small = "some guid B" }
}
```

Which is obviously incorrect. The parser seems to get confused by the "." in the service plan name.

I am using https://github.com/mevansam/terraform-provider-cf/releases/tag/0.9.5 and Terraform 0.11.0

**Comment by mevansam** [comment]
This parsing issue occurs because Terraform interprets the "." as a delimiter for child elements within the output map. Would translating "." in the plan name to "_" be acceptable?

**Comment by chrismathias** [comment]
You mean the data.cf_service.sv_database.service_plans would then be
```
{
  v3_0-dev = "some guid A"
  v3_0-dev-small = "some guid B"
}
```

Yes, that would be okay. Then we could take this into account when accessing the map keys.

**Comment by chrismathias** [comment]
Hi,

I finally got around to testing this - works beatifully. Thanks a lot!
